In [1]:
import numpy as np

In [2]:
#q1
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Original array:", arr)

# a) Add 2 to all elements
print("After adding 2:", arr + 2)

# b) Multiply 3 with all elements
print("After multiplying by 3:", arr * 3)

# c) Divide every element by 2
print("After dividing by 2:", arr / 2)

Original array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
#q2a
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Reversed array:", arr[::-1])

Reversed array: [5 4 6 3 2 1]


In [4]:
#q2b
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

value = 1

print("Most frequent value:", value)
print("Indices:", np.where(x == value)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [5]:
#q2b
y = np.array([1, 1, 1, 2, 3, 4, 2, 3, 3, 3, 1])

value = 1
print("Most frequent value:", value)
print("Indices:", np.where(y == value)[0])

Most frequent value: 1
Indices: [ 0  1  2 10]


In [6]:
#q3
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# a) 1st row, 2nd column
print(arr[0, 1])

# b) 3rd row, 1st column
print(arr[2, 0])

20
70


In [9]:
#q4
import numpy as np

pankhil = np.linspace(10, 100, 25)

print("Array:", pankhil)
print("Shape:", pankhil.shape)
print("Total elements:", pankhil.size)
print("Data type:", pankhil.dtype)
print("Total bytes:", pankhil.nbytes)

# Convert into 5 x 5
pankhil = pankhil.reshape(5, 5)

print("5 x 5 array:")
print(pankhil)

# Transpose
print("Transpose:")
print(pankhil.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
5 x 5 array:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]
Transpose:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [8]:
#q5
import numpy as np

ucs420_pankhil = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Array:")
print(ucs420_pankhil)

print("Mean:", np.mean(ucs420_pankhil))

print("Median:", np.median(ucs420_pankhil))

print("Maximum:", np.max(ucs420_pankhil))

print("Minimum:", np.min(ucs420_pankhil))

print("Unique elements:", np.unique(ucs420_pankhil))

reshaped_ucs420_pankhil = ucs420_pankhil.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_pankhil)

resized_ucs420_pankhil = np.resize(ucs420_pankhil, (2, 3))

print("Resized array:")
print(resized_ucs420_pankhil)

Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
