In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr + 2)
print(arr * 3)
print(arr / 2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print(arr[::-1])

[5 4 6 3 2 1]


In [3]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

value = np.bincount(x).argmax()

print("Most frequent value:", value)
print("Indexes:", np.where(x == value)[0])

Most frequent value: 1
Indexes: [0 5 7 8 9]


In [4]:
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

value = np.bincount(y).argmax()

print("Most frequent value:", value)
print("Indexes:", np.where(y == value)[0])

Most frequent value: 1
Indexes: [0 1 2]


In [5]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0, 1])
print(arr[2, 0])

20
70


In [6]:
import numpy as np

arr = np.linspace(1, 100, 25)

print("Array:", arr)
print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Total bytes:", arr.nbytes)

transpose = arr.reshape(5, 5)

print("Transpose:", transpose.T)

Array: [  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose: [[  1.     21.625  42.25   62.875  83.5  ]
 [  5.125  25.75   46.375  67.     87.625]
 [  9.25   29.875  50.5    71.125  91.75 ]
 [ 13.375  34.     54.625  75.25   95.875]
 [ 17.5    38.125  58.75   79.375 100.   ]]


In [7]:
import numpy as np

ucs420_hitanshi = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_hitanshi))
print("Median:", np.median(ucs420_hitanshi))
print("Maximum:", np.max(ucs420_hitanshi))
print("Minimum:", np.min(ucs420_hitanshi))

reshaped_ucs420_hitanshi = ucs420_hitanshi.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_hitanshi)

resized_ucs420_hitanshi = ucs420_hitanshi.reshape(2, 6)

print("Resized array:")
print(resized_ucs420_hitanshi)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
